### ISSUE TITLE
How to prevent token from expiring?

### ISSUE THREAD

**Issue by DennisGarvey** [Jeff77789/FlexpoolMinerStats#1]
The script stops working after 3 days and requires me to reauthenticate with oauth

**Comment by razedavid** [comment]
same issue, maybe 7 days for me had to delete the sheets.googleapis.com-python.json and retrigger google authentication again.

**Comment by Jeff77789** [comment]
I'm guessing the console printout that you guys are receiving is similar to exceptions.RefreshError 'invalid_grant: Token has been expired or revoked.'

I read [here](https://forum.rclone.org/t/google-drive-cannot-refresh-token-after-a-few-days/22036/16) that if you leave the status of your app in "testing" then the token would expire every 7 days or so. If you visit your Google api OAuth consent screen and publish app hopefully this will fix your issue.

Another possible cause is a time sync issue between your machine and the google servers
